services:
  # A Django web service
  - type: web
    name: kapadia-school
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn kapadiaschool.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
        # Set this to your Neon database URL in the Render dashboard
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SUPABASE_URL
        sync: false
        # Add your Supabase URL from the Supabase dashboard
        # Example: https://yourproject.supabase.co
      - key: SUPABASE_KEY
        sync: false
        # Add your Supabase anon/public key from the Supabase dashboard API section
