services:
  # A Django web service
  - type: web
    name: kapadia-school
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: kapadia-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
        # Add your Supabase URL from the Supabase dashboard
        # Example: https://yourproject.supabase.co
      - key: SUPABASE_KEY
        sync: false
        # Add your Supabase anon/public key from the Supabase dashboard API section

# A PostgreSQL database
databases:
  - name: kapadia-db
    databaseName: kapadia_school
    user: kapadia_school_user
    plan: free
    postgresMajorVersion: 14  # Specify PostgreSQL version for better compatibility
