# Generated by Django 6.0.3 on 2026-05-02 12:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0008_remove_supabase_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-friendly identifier, e.g., chattral, chandkheda', unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Campus Name')),
                ('board', models.CharField(blank=True, max_length=20, verbose_name='Board')),
                ('affiliation_number', models.CharField(blank=True, max_length=50, verbose_name='Affiliation Number')),
                ('timings', models.CharField(blank=True, max_length=100, verbose_name='Timings')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='campus/photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Campus Photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuses',
                'ordering': ['name'],
                'permissions': [('change_campus_photo', 'Can change campus photo')],
            },
        ),
        migrations.CreateModel(
            name='CampusDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='campus/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF Document')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Campus Document',
                'verbose_name_plural': 'Campus Documents',
                'ordering': ['campus', 'order'],
            },
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='date',
            field=models.DateTimeField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='festival/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='celebration',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Feature on Homepage'),
        ),
        migrations.AlterField(
            model_name='celebrationphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='festival/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('festival', 'Festival'), ('event', 'School Event'), ('sports', 'Sports Event'), ('cultural', 'Cultural Event'), ('academic', 'Academic Event'), ('other', 'Other')], db_index=True, default='other', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Feature on Homepage'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Image'),
        ),
        migrations.AddIndex(
            model_name='celebration',
            index=models.Index(fields=['celebration_type', '-date'], name='khschool_ce_celebra_c01294_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['category', '-date_created'], name='khschool_ga_categor_7ebf33_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['is_featured', '-date_created'], name='khschool_ga_is_feat_23b767_idx'),
        ),
        migrations.AddField(
            model_name='campusdocument',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='khschool.campus'),
        ),
    ]
