# Generated by Django 6.0.5 on 2026-05-26 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0011_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebration',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebrations', to='khschool.campus', verbose_name='Campus'),
        ),
    ]
