# Generated by Django 4.2.30 on 2026-09-23 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khschool', '0012_celebration_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='campus',
            field=models.ForeignKey(blank=True, help_text='Which campus this enquiry is about (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to='khschool.campus', verbose_name='Campus'),
        ),
    ]
